# Generated by Django 4.1.3 on 2022-11-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkSaveApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Phone_1_Value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
