# Generated by Django 4.1.3 on 2022-11-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulkSaveApp', '0003_remove_contacts_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='user',
        ),
    ]
