# Generated by Django 4.1.3 on 2022-11-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulkSaveApp', '0004_remove_contacts_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='AllContacts',
        ),
    ]
