# Generated by Django 4.1.3 on 2022-11-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkSaveApp', '0005_rename_contacts_allcontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='testModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('yourclass', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
            ],
        ),
    ]
