# Generated by Django 4.1.3 on 2022-11-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulkSaveApp', '0007_rename_name_allcontacts_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcontacts',
            old_name='Phone_Numer',
            new_name='Phone_Nubmer',
        ),
    ]
