# Generated by Django 4.1.3 on 2022-11-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkSaveApp', '0008_rename_phone_numer_allcontacts_phone_nubmer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allcontacts',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='allcontacts',
            name='Phone_Nubmer',
        ),
        migrations.RemoveField(
            model_name='allcontacts',
            name='edited_at',
        ),
        migrations.AddField(
            model_name='allcontacts',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
