# Generated by Django 4.1.3 on 2022-11-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulkSaveApp', '0009_alter_allcontacts_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcontacts',
            old_name='FirstName',
            new_name='FullName',
        ),
        migrations.RenameField(
            model_name='allcontacts',
            old_name='LastName',
            new_name='Phone_Number2',
        ),
    ]
