# Generated by Django 4.1.3 on 2022-11-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkSaveApp', '0010_rename_firstname_allcontacts_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('Signature', models.CharField(max_length=200)),
                ('Title', models.CharField(blank=True, max_length=2000, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('Phone_Number', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['edited_at', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='testModel',
        ),
        migrations.AddField(
            model_name='allcontacts',
            name='Signature',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
