# Generated by Django 4.1.3 on 2022-11-29 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulkSaveApp', '0011_startlist_delete_testmodel_allcontacts_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='startlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
