# Generated by Django 4.1.3 on 2022-12-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkSaveApp', '0014_remove_signupmodel_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='startlist',
            name='Access',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
