# Generated by Django 4.1.3 on 2022-12-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulkSaveApp', '0015_startlist_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startlist',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='startlist',
            name='Username',
        ),
    ]
